- name: Copy repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install logstash
  ansible.builtin.dnf:
    name: logstash
    state: latest

- name: Copy logstash config file
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Start Logstash
  ansible.builtin.systemd_service:
    name: logstash
    state: started
    enabled: true