- name: Backend Setup
  hosts: all
  become: yes
  tasks:
    - name: Disable default NodeJS version module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJS module
      ansible.builtin.shell: dnf module enable nodejs -y

    - name: Install NodeJS
      ansible.builtin.dnf:
        name:  nodejs
        state: latest

    - name: Copy Backend Service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Add Expense User
      ansible.builtin.user:
        name: expense

    - name: Remove Old App Content
      ansible.builtin.file:
        name: /app
        state: absent

    - name: Create a directory
      ansible.builtin.file:
        name: /app
        state: directory

    - name: Download and Extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Install NodeJS dependencies
      community.general.npm:
        path: /app
        state: latest

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
        state: latest

    - name: Install Python MySQL and Cryptography
      ansible.builtin.pip:
        name:
          - PyMySQL
          - cryptography
        executable: pip3.9

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: IP_Address

    - name: Start Backend Service
      ansible.builtin.systemd_service:
        name: backend
        enabled: yes
        state: restarted
        daemon_reload: yes