- name: MySQL Setup
  hosts: all
  become: yes
  tasks:
    - name: Install MySQL Server
      ansible.builtin.dnf:
        name: mysql-server
        state: latest

    - name: Start MySQL Service
      ansible.builtin.systemd_service:
        name: mysqld
        enabled: yes
        state: started

    - name: Setup root password
      ansible.builtin.shell: mysql_secure_installation --set-root-pass AppExpense@1
