- name: Install Terraform
  hosts: all
  become: true
  tasks:
    - name: Install Terraform
      yum:
        name: terraform
        state: latest

    - name: Terraform Version
      ansible.builtin.shell: terraform -version