- name: Install Terraform
  hosts: all
  become: true
  tasks:
    - name: Install Terraform
      ansible.builtin.yum_repository:
        name: hashicorp
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    - name: Terraform Version
      ansible.builtin.dnf:
        name: terraform
        state: present