- name: Install Terraform
  hosts: all
  become: true
  tasks:
    - name: Add HashiCorp YUM Repository
      ansible.builtin.yum_repository:
        name: hashicorp
        description: HashiCorp YUM Repository
        baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    - name: Terraform Installation
      ansible.builtin.shell: dnf install terraform
