- name: Disable default NodeJS version module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJS module
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Install NodeJS
  ansible.builtin.dnf:
    name:  nodejs
    state: latest

- name: Copy Backend Service
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add Expense User
  ansible.builtin.user:
    name: expense

- name: Import roles and tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Install NodeJS dependencies
  community.general.npm:
    path: /app
    state: latest

- name: Install Python PyMySQL and Cryptography
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: "{{mysql_root_password}}"
    login_host: mysql-{{env}}.devopsjourney.fun

- name: Import roles and tasks from NewRelic
  ansible.builtin.import_role:
    name: newrelic
    tasks_from: nodejs

- name: Start Backend Service
  ansible.builtin.systemd_service:
    name: backend
    enabled: yes
    state: restarted
    daemon_reload: yes