format_version: 10
pipelines:
  mysql:
    group: defaultGroup
    materials:
      git-b844969:
        git: https://github.com/DevOps-iteration2/expense-ansible.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      vault_token: AES:M5sHrn101ghkZuiQ0rUtfQ==:Pv9yJ08KyNWzUcOYPiVJWXAqnoz2aEYE6ksDOGvhgekEYXSZtbBbIvD/L+VxUbNx
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env : dev
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash #bash ansible.sh
                    run_if: passed
      - QA :
          fetch_materials: true
          environment_variables:
            env: qa
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash #bash ansible.sh
                    run_if: passed
      - STAGE:
          fetch_materials: true
          environment_variables:
            env: stage
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash #bash ansible.sh
                    run_if: passed
      - PROD:
          fetch_materials: true
          environment_variables:
            env: prod
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - mysql
                    command: bash #bash ansible.sh
                    run_if: passed