- name: Download Node Exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    owner: bin
    remote_src: yes

- name: Copy Node Exporter Service file
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Node Exporter Service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    daemon_reload: true
    enabled: true
