- name: Set prompt with component
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }} # we can use variables directly unlike terraform

- name: Import Node Exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

- name: Import Logstash
  ansible.builtin.import_role:
    name: logstash

- name: Import rsyslog
  ansible.builtin.import_role:
    name: rsyslog
  when: rsyslog_config_needed